version: "3.9"

services:
  api:
    build: .
    container_name: football-manager-api
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: fantasy
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: secret123

  db:
    image: postgres:15
    container_name: football-manager-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasy
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: football-manager-redis
    ports:
      - "6379:6379"
